export const getRouteHome = () => '/'
export const getRouteAuth = () => '/auth'
export const getRouteProfile = () => '/profile'
export const getRouteCart = () => '/cart'
export const getRouteCheckout = () => '/checkout'
export const getRouteSale = () => '/sale'
export const getRouteNew = () => '/new'
