export { ReviewCard } from './ui/ReviewCard/ReviewCard'
export { ReviewCardSkeleton } from './ui/ReviewCard/ReviewCardSkeleton'
export { ReviewsList } from './ui/ReviewsList/ReviewsList'
export type { Review } from './types/reviewsSchema'
export { useGetHighRatingReviewsQuery, useLazyGetReviewsByProductIdQuery, useAddReviewMutation } from './api/reviewApi'
