export { ReviewCard } from './ui/ReviewCard/ReviewCard'
export { ReviewCardSkeleton } from './ui/ReviewCard/ReviewCardSkeleton'
export { ProductReviews } from './ui/ProductReviews/ProductReviews'
export { ProductReviewsSkeleton } from './ui/ProductReviews/ProductReviewsSkeleton'
export type { Review, ReviewsSchema } from './model/types/reviewsSchema'
export { useGetHighRatingReviewsQuery, useLazyGetReviewsByProductIdQuery } from './api/reviewApi'
export { useReviewsActions, reviewsActions, reviewsReducer } from './model/slice/reviewsSlice'
