export { shopRoutes } from './shopRoutes'
export { navbarRoutes } from './navbarRoutes'
export { actionRoutes } from './actionRoutes'
export { styleRoutes } from './styleRoutes'
export { companyRoutes } from './companyRoutes'
export { helpRoutes } from './helpRoutes'
export { FAQRoutes } from './FAQRoutes'
export { resourcesRoutes } from './resourcesRoutes'
